apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: fandvrag-ingest
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - name: ingest
              image: gcr.io/PROJECT_ID/fandvrag-ingest
              env:
                - name: DATA_DIR
                  value: "/data"
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: openai-api-key
                      key: key
                - name: SUPABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: supabase-url
                      key: url
                - name: SUPABASE_SERVICE_ROLE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: supabase-service-key
                      key: key
              volumeMounts:
                - name: data-volume
                  mountPath: /data
          volumes:
            - name: data-volume
              emptyDir: {}
          restartPolicy: Never
      backoffLimit: 3
