steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/fandvrag-server", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fandvrag-server"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "fandvrag-server"
      - "--image"
      - "gcr.io/$PROJECT_ID/fandvrag-server"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"

images:
  - "gcr.io/$PROJECT_ID/fandvrag-server"
